apiVersion: v1
kind: ServiceAccount
metadata:
  name: cgnet-exporter
  labels:
    k8s-app: cgnet-exporter
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cgnet-exporter
  labels:
    k8s-app: cgnet-exporter
rules:
  - apiGroups: [ "*" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cgnet-exporter
  labels:
    k8s-app: cgnet-exporter
subjects:
  - kind: ServiceAccount
    name: cgnet-exporter
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cgnet-exporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cgnet-exporter
  namespace: kube-system
  labels:
    k8s-app: cgnet-exporter
spec:
  template:
    metadata:
      name: cgnet-exporter
      labels:
        k8s-app: cgnet-exporter
    spec:
      containers:
      - name: cgnet-exporter
        image: robertgzr/cgnet-exporter:latest
        # imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - containerPort: 9101
          hostPort: 9101
          name: scrape
      hostNetwork: true
      hostPID: true
      serviceAccountName: cgnet-exporter
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: cgnet-exporter
  name: cgnet-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9101
    protocol: TCP
  selector:
    k8s-app: cgnet-exporter
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: cgnet-exporter
  labels:
    k8s-app: cgnet-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: cgnet-exporter
  endpoints:
  - port: http-metrics
    interval: 30s
