apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cgnet-exporter
  namespace: kube-system
  labels:
    k8s-app: cgnet-exporter
spec:
  template:
    metadata:
      name: cgnet-exporter
      labels:
        k8s-app: cgnet-exporter
    spec:
      containers:
      - name: cgnet-exporter
        image: robertgzr/cgnet-exporter:latest
        # imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - containerPort: 9101
          hostPort: 9101
          name: scrape
      hostNetwork: true
      hostPID: true
      serviceAccountName: cgnet-exporter
  updateStrategy:
    type: RollingUpdate
