apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: cgnet-exporter
  name: cgnet-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9101
    protocol: TCP
  selector:
    k8s-app: cgnet-exporter
