apiVersion: v1
kind: ServiceAccount
metadata:
  name: cgnet-exporter
  labels:
    k8s-app: cgnet-exporter
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cgnet-exporter
  labels:
    k8s-app: cgnet-exporter
rules:
  - apiGroups: [ "*" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cgnet-exporter
  labels:
    k8s-app: cgnet-exporter
subjects:
  - kind: ServiceAccount
    name: cgnet-exporter
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cgnet-exporter
  apiGroup: rbac.authorization.k8s.io
